version: 2.1
orbs:
  node: circleci/node@4.6.0
  ruby: circleci/ruby@1.1.4

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch
    executor: ruby/default
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
