version: 2.1
orbs:
  node: circleci/node@4.6.0
  ruby: circleci/ruby@1.1.4

jobs:
  build:
    docker:
      - image: 'cimg/base:stable'
    executor: ruby/default
    steps:
      - checkout
      - ruby/install:
          version: '2.6.3'
      - ruby/install-deps
      - node/install:
          install-yarn: true
      - node/install-packages:
          pkg-manager: yarn
      - ruby/rspec-test
